import Head from "next/head";
import styles from "@styles/Home.module.css";
import { NextPage } from "next";
import useSWR from "swr";
import axios, { AxiosInstance, AxiosRequestConfig } from "axios";

type FetcherArgs = {
  url: string;
};

type PilotInfo = {
  name: string;
  emailAddress: string;
  phoneNumber: string;
};

type SWRReturn = {
  data: PilotInfo[];
  error?: any;
};

const axiosInstance: AxiosInstance = axios.create({});

const fetcher = async ({ url }: FetcherArgs) => {
  const request: AxiosRequestConfig = {
    url: url,
    method: "GET",
    responseType: "json",
  };
  const response = await axiosInstance.request(request);

  return response.data;
};

const Home: NextPage<null> = () => {
  const { data: pilots, error: error }: SWRReturn = useSWR(
    { url: "api/pilots" },
    fetcher
  );

  if (error)
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <div>Lol</div>
        </main>
      </>
    );
  if (!pilots)
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <div>Loading</div>
        </main>
      </>
    );

  console.log(pilots);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <h1>Works</h1>
          {pilots.map((pilot) => (
            <p>{pilot.name}</p>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
