import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { NextPage } from "next";
import useSWR from 'swr';
import axios, { AxiosInstance, AxiosRequestConfig } from "axios";

type FetcherArgs = {
  url: string,
  responseType: "json" | "document",
}

const axiosInstance: AxiosInstance = axios.create({});

const fetcher = async ({ url, responseType }: FetcherArgs) => {
  const request: AxiosRequestConfig = {
    url: url,
    method: "GET",
    responseType: responseType,
  };
  const response = await axiosInstance.request(request);

  if ( url === "/birdnest/drones" ) {
    return response.data;
  } else {
    return response.data;
  }
};

const Home: NextPage<null> = () => {
  const { data: drones, error: droneError } = useSWR({ url: 'birdnest/drones', responseType: "document"}, fetcher, { refreshInterval: 2000 });
  const { data: pilots, error: pilotError } = useSWR({ url: 'birdnest/pilots/SN-rCkQs9fKmd', responseType: "json"}, fetcher);

  if (droneError) return (  
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className={styles.main}>
      <div>
        Lol
      </div>
    </main>
  </>    
  )
  if (!drones) return (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className={styles.main}>
      <div>
        Loading
      </div>
    </main>
  </> 
  )

  if (pilots) {
    console.log(pilots);
  }
  console.log(drones);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          Works
        </div>
      </main>
    </>
  )
}

export default Home;